### ISSUE TITLE
App crashes when HA instance is unavailable

### ISSUE THREAD

**Issue by hugodejong** [home-assistant/home-assistant-android#113] opened 2019-12-05 12:24 UTC
The app crashes on start-up if the HA instance is currently unavailable. The reason doesn't matter: happens in case of an IP ban (403 forbidden), HA outage, misconfigured Nginx, anything else, it's all the same.

**Comment by balloob** [comment] 2019-12-05 16:16
Duplicate of #79

**Closed by balloob** 2019-12-05 16:16 UTC
Labels: bug
