### ISSUE TITLE
Add support for internal (LAN) AND external (i.e. nabu.casa) web URL

### ISSUE THREAD

**Issue by ciejepro** [home-assistant/home-assistant-android#207] opened 2019-12-26 18:57 UTC
**Home Assistant Android version:**

**Android version:**
8.8.8

**Phone model:**
LG G6

**Home Assistant version:**
1.3.1 (57)

**Last working Home Assistant release (if known):**

**Description of problem:**
App only accepts single URL.  Internal (LAN URL https://<IPaddress>:8123) did not work.  Only the external nabu.casa address worked.

**Traceback (if applicable):**

```

```

**Additional information:**
This is fine as long as the home internet connection is up and operational.  If internet at home is down, this will break the app.  This is the only reason why the Ariela app is safer to use, it has both an internal and external address function.  Rendering of HA frontend is better in the native app.

**Comment by allanpersson** [comment] 2019-12-26 18:59
Duplicate of https://github.com/home-assistant/home-assistant-android/issues/30

**Closed** 2019-12-27 08:16 UTC
