### ISSUE TITLE
Privacy option

### ISSUE THREAD

**Issue by erlanger** [home-assistant/home-assistant-android#412] opened 2020-02-13 13:20 UTC
**Home Assistant Android version:**
1.7.0
**Android version:**
9
**Phone model:**
moto x4
**Home Assistant version:**
105.3
**Last working Home Assistant release (if known):**
1.6
**Description of problem:**

I posted this in a comment for PR #370, but I think it should rather be an issue.
I was running home assistant companion in lineageos without problems, but PR #370  breaks it.
The app gets stuck in a loop "unable to register app". 

* My guess is that this is happening because I am _not using google services_ as I want my data privacy instead of google spying on my home
* In version 1.6 I also had the "unable to register app" message, but I restarted the app and it connected properly (although I had to give up notifications)

Please keep this option open for those who are willing to give up notification in order to avoid using google services (e.g. firebase).

I am back to 1.6.

Thanks for the great work!

**Traceback (if applicable):**

```

```

**Additional information:**

**Comment by JBassett** [comment] 2020-02-13 13:25
Duplicate of https://github.com/home-assistant/home-assistant-android/issues/358

**Closed by JBassett** 2020-02-13 13:25 UTC

**Comment by erlanger** [comment] 2020-02-13 13:37
@JBassett,

   Thans for your prompt answer, but this is not really a duplicate. #358 (and related issues). Those issues  are about running the app without google services and **maintaining notifications**, with perhaps your own inhouse protocol. My issue is different.

All I want is the app to continue working as it was working in 1.6; I am willing to give up notifications.

**Comment by balloob** [comment] 2020-02-13 16:26
That's not something we're going to support.

**Comment by Extarys** [comment] 2020-06-15 01:41
OpenHAB looks more attractive now, thanks!

**Comment by mecko** [comment] 2020-06-15 13:20
The devs repeatedly declared they have no intention to support devices without official Google services, despite home assistant's privacy-first moto. Answers were not given and discussions were locked. They sent us our way and suggested that we fork the project.

If you have microG, nearly all functionalities (everything except push notifications as far as I noticed) work just fine, including location and geofencing. Look here: [mecko/home-assistant-android-microg](https://github.com/mecko/home-assistant-android-microg).

If you chose not to use microG either, then look at forks that removed Google functionality altogether like [jleeuwes/home-assistant-android-without-google](https://github.com/jleeuwes/home-assistant-android-without-google). Less features work there, but the app works.

**Comment by erlanger** [comment] 2020-06-26 17:44
What is really sad is that the home page for [home-assistant](https://www.home-assistant.io/) says:
> Open source home automation that puts local control **and privacy first**. 

At least the part that says that they put privacy first should be erased. @Extarys, as you say, OpenHAB is looking more and more attractive.
