### ISSUE TITLE
Does not work when in local network

### ISSUE THREAD

**Issue by rPonuganti** [home-assistant/home-assistant-android#331] opened 2020-02-01 14:50 UTC
**Home Assistant Android version:** 1.5.1 (97)

**Android version:** 9

**Phone model:** Samsung Galaxy S8 (SM-G950F)

**Home Assistant version:** 0.104.3 (running on Hassio)

**Last working Home Assistant release (if known):** None

**Description of problem:**

I have configured the correct WiFi SSID and the Internal Connection URL, but App does not work on local WiFi network. It simply shows the error "Unable to connect to Home Assistant."

On external network work flawless. I have been trying to get it work and waited for a update too, but didn't work. 

I am attaching the screenshots of the error.
![Screenshot_20200130-214221_Home Assistant](https://user-images.githubusercontent.com/2393528/73594013-64b82280-450a-11ea-8499-57a8e1ddbfad.jpg)
![Screenshot_20200130-214401_Home Assistant](https://user-images.githubusercontent.com/2393528/73594014-6550b900-450a-11ea-85bc-51fbeb988b17.jpg)
![Screenshot_20200131-065623_Settings](https://user-images.githubusercontent.com/2393528/73594015-6550b900-450a-11ea-8e98-62ee49548686.jpg)

**Traceback (if applicable):**

```

```

**Additional information:**

**Comment by JBassett** [comment] 2020-02-02 05:04
Can you show a screenshot of you connected locally in the browser?  My initial guess is this is a duplicate of https://github.com/home-assistant/home-assistant-android/issues/314

**Comment by balloob** [comment] 2020-02-02 05:25
Yeah, you can't use `https` locally with IP. The certificate is bound to your duckdns url.

**Closed by balloob** 2020-02-02 05:25 UTC

**Comment by rPonuganti** [comment] 2020-02-02 08:01
Yes. Looks like its a duplicate of #314. With local IP I am using http.
Just now checked, in my browser am using https and does not work with http.
I am attaching both the screenshots. 
![Screenshot_20200202-085637_Chrome](https://user-images.githubusercontent.com/2393528/73605108-6fba9380-459a-11ea-8ded-f7e4ed55a98a.jpg)
![Screenshot_20200202-085557_Chrome](https://user-images.githubusercontent.com/2393528/73605114-7b0dbf00-459a-11ea-88fe-b2464b815696.jpg)

I will try out the instructions in #314. I will give an update. 
Thanks for your support.

**Comment by rPonuganti** [comment] 2020-02-02 10:44
It works by following the instructions in #314. Thanks for the the info.
Sorry, I do not know why I didn't find 314 during my initial search.
