### ISSUE TITLE
No connection timeout - cannot reconnet to my instance

### ISSUE THREAD

**Issue by MarcJenningsUK** [home-assistant/home-assistant-android#77] opened 2019-11-27 12:18 UTC
Recently moved my HA server to a new IP address on a new network.  I cannot change the settings in the app to view the new address.  I just see a blank screen as it tries to find the old address.

**Comment by balloob** [comment] 2019-11-27 23:46
Duplicate of #71

**Closed by balloob** 2019-11-27 23:46 UTC
