### ISSUE TITLE
App not "re-linked" to the existing integration

### ISSUE THREAD

**Issue by SeLLeRoNe** [home-assistant/home-assistant-android#262] opened 2020-01-16 13:31 UTC
**Home Assistant Android version:**
1.3.1 (77)
**Android version:**
9 (Oxygen OS 9.0.9)
**Phone model:**
OnePlus 5
**Home Assistant version:**
0.104.0
**Last working Home Assistant release (if known):**

**Description of problem:**
Once I logout from HA, the integration for the phone disappear from the list, as soon as I login again a new one is created (while the previous one doesn't appear anymore).
Beside the fact that it was supposed to be a new "feature" of latest Android App with HA 0.104.0+, it doesn't even allow me to rename the device as it was before, because the previous entity is somewhere still present in the system (even if it is not showed).
![image](https://user-images.githubusercontent.com/9599441/72528945-8491ea00-386c-11ea-8155-17694cebdd19.png)

Of course, once I restart HA I am able to rename the device again, but my understanding was that this was no longer necessary because of the unique ID HA should assign to a device, and re-use it (and presumably all the settings assigned to it) once the device log back in.
**Traceback (if applicable):**

```

```

**Additional information:**

**Comment by dshokouhi** [comment] 2020-01-16 20:59
I think that will only work once a new integration was created in 0.104 because that was when unique ID was added to config flows but I could be mistaken :)

**Comment by SeLLeRoNe** [comment] 2020-01-16 21:01
No that's not the case, I made sure to remove the old integration, restart and then login "as new device" before I started the test.

It was technically a new device with latest HA App and Server, it should have worked in my opinion.

I might be wrong :)

**Comment by dshokouhi** [comment] 2020-01-16 21:08
Yea to my understanding it was once the new config flow was created in 0.104 then if you went to the android app and cleared data and logged back in it should use the same entry instead of creating a second one.

**Comment by gadgetchnnel** [comment] 2020-01-18 21:33
I've just had the same thing happen. The steps to reproduce it are:

1. Logon to HA (version 0.104 or later) in the mobile app
2. Rename the device_tracker entity within Integrations
3. Log out of the app and log back in
4. Try to change the device_tracker entity again (as it has reset to the original default)

This will give the "Entity is already registered" error as above.
Restarting Home Assistant after logging in the second time allows it to be renamed, so it seems the issue is twofold:

1. When re-linking to an existing integration, any entity renames are not retained and the default entity id (based on phone model) is used
2. The old renamed entity is retained until HA is restarted

**Comment by SeLLeRoNe** [comment] 2020-01-19 11:11
Just a note which in my opinion makes sense.

Once I register a device and configure name and entity, the device should be assigned an unique ID which is stored in the App.

This ID should be mantained even on logout, it should be lost only on App uninstallation process.

Once a phone login, it will send this ID to HA (if present), and HA wilkl match to an internal DB to retrieve device and entity name, setting this inside HA and sending those info to the Phone so that technically, the user should have nothing to change and all his settings should be restored (ex. tracking config, device name, entity name, phone name, etc.)

Of course inside HA a Phone can be "decommisioned" removing the integration as for now, so that if you want HA to "lose" all the pre-configuration for a specific phone, you can.

**Comment by balloob** [comment] 2020-01-20 01:54
Yo... This is exactly how it works....

**Comment by JBassett** [comment] 2020-01-20 03:50
So it looks like the integration gets linked but the device tracker doesn't link back up.  However it does look like the old device tracker entity gets removed from the integration but not cleaned up else where leading you to be unable to change the name to the original id.

**Comment by balloob** [comment] 2020-01-20 06:03
This might help https://github.com/home-assistant/home-assistant/pull/30995

**Comment by SeLLeRoNe** [comment] 2020-01-20 10:06
I wasn't sure that's how it works, I just gave my personal opinion on how it should work based on my IT experience :)
Wasn't sure was designed that way or my words could have simply worked as "triggers" for a new idea :)

**Comment by balloob** [comment] 2020-02-11 04:31
Should be fixed in 105. Requires both times to be onboarded on 105+.

**Closed by balloob** 2020-02-11 04:31 UTC
