### ISSUE TITLE
Fallback to remote.nabucasa.com when local connection is not available

### ISSUE THREAD

**Issue by ekt-** [home-assistant/home-assistant-android#237] opened 2020-01-08 15:17 UTC
If I'm at home, I'd prefer to use the local connection since is faster.
When I'm away, the app should automatically connect via nabucasa

**Comment by allanpersson** [comment] 2020-01-09 11:33
Duplicate of #30 !? 🙏

**Comment by JBassett** [comment] 2020-01-09 12:20
Duplicate: #30

**Closed by JBassett** 2020-01-09 12:20 UTC
Labels: duplicate

**Comment by ekt-** [comment] 2020-01-09 13:38
#30 didn't came up in my search probably because was already closed. I see it's implemented in #209, which is great. Thanks
