### ISSUE TITLE
Actual theme aligned status/navigation bar coloring

### ISSUE THREAD

**Issue by Tamas-Toth-ebola** [home-assistant/home-assistant-android#541] opened 2020-04-02 17:34 UTC
**Is your feature request related to a problem? Please describe.**

Hello!

The app currently - as all normal Android app - recolor the Android's status/navigation bar on the top of the screen with the primary color, or the header color of the main HA - GUI itself. This is perfect until - as HA generally us theming possibilities - we do not use custom themes. But if we do the recolored status/navigation bar will be off. If we use dark themes the default HA brand blue is absolutely off and burning on the top of the screen.

**Describe the solution you'd like**

Could it be possible to use the actual theme's primary color/header color for recoloring Android's status/navigation bar?

Thanks for your answer in advance!

**Describe alternatives you've considered, if any**

**Additional context**

**Comment by dshokouhi** [comment] 2020-04-02 17:42
@Tamas-Toth-ebola you will need to call `frontend.set_theme` for the status bar to properly update for the time being.

There are also 2 feature requests that will do what you ask so closing this as duplicate of #524 and #272

**Closed by dshokouhi** 2020-04-02 17:42 UTC
Labels: enhancement
