### ISSUE TITLE
GAPPS required? Option for no GAPPS?

### ISSUE THREAD

**Issue by ministryofsillywalks** [home-assistant/home-assistant-android#358] opened 2020-02-10 18:01 UTC
**Home Assistant Android version:**
1.6.0 (105)
**Android version:**
9 (MicroG Lineage Build)
**Phone model:**
Pocophone
**Home Assistant version:**
105
**Last working Home Assistant release (if known):**
-
**Description of problem:**
I wanted to try out the new notification feature, however I can't push any notifications to my phone.
The phone shows up under integrations and the "notify.mobile_app_<device_id> is also created and updated just fine.
I installed the app on a different phone with the same procedure and it worked immediately.
The only difference in the setup is, that my main phone runs a microG build, which removes gapps and play services and implements a proxy for some requirements and uses the unifiedNLP for location and backend.
It normally mimics gapps well enough and notifications work for most apps (whatsapp, mail, telegram, etc) but some apps have issues with the missing gapps. 

I highly suspect this is the cause of my problems and I would love to see the app work without gapps (what with the whole idea of home-assistant being to take the data into your own hands and not leave it with google and co. ;) )

Happy to test stuff out if you need me to.

**Traceback (if applicable):**

```

```

**Additional information:**
MicroG homepage for more information on the project:
https://microg.org/

**Comment by balloob** [comment] 2020-02-10 19:02
Duplicate of #231. See https://github.com/home-assistant/home-assistant-android/issues/231#issuecomment-571339442

**Closed by balloob** 2020-02-10 19:02 UTC
