### ISSUE TITLE
No found my HA in my network by WiFI

### ISSUE THREAD

**Issue by pepeEL** [home-assistant/home-assistant-android#110] opened 2019-12-04 21:49 UTC
Hi I try auto connect my Android app with HA but he not found my HA automatically. I must config manual ? Why ? I am in the same network as Home Assistant and connected by WIFI in my home.

**Comment by balloob** [comment] 2019-12-04 21:51
Duplicate of #64

**Closed by balloob** 2019-12-04 21:51 UTC
