### ISSUE TITLE
Notifications with multiple devices of same model

### ISSUE THREAD

**Issue by mgrefsrud** [home-assistant/home-assistant-android#170] opened 2019-12-18 06:58 UTC
My setup:
Android app ver.1.2.0 (42)
Andriod 9
Huawei mate 20 pro
Homa assistant (Hassio) 103.0

I have set up the new very nice Andriod app, and it works great, but i have two Huawei Mate 20 pro (LYA-L29) devices that use the app, and because the notification path refers to the device model i only am able to send notifications to the first device i integrated.  I have tried to edit the device name in core_device_registry but this is overwritten. I do not see any other possibility to change the device name to be unique  some other place either.
My suggestion is to have in the app the possibility to give each device a unique name, like the IOS app has, this would solve this issue i think.

**Comment by allanpersson** [comment] 2019-12-18 07:37
Duplicate of https://github.com/home-assistant/home-assistant-android/issues/149 ?

**Comment by reharmsen** [comment] 2019-12-19 21:23
Already implemented with #158, and thus released with 1.3.0 ?

**Closed** 2019-12-20 09:43 UTC

**Comment by Wilco89** [comment] 2019-12-20 13:02
Version. 1.3.0

I do have same problem, do have 2x galaxy s9, but even with the use of device name, I only get one, notify.mobile_app_sm_g960f

Tried to disconnect and reconnect my device. Did restart multiple times. But now my girlfriend does get the notifications.

**Comment by JBassett** [comment] 2019-12-20 13:12
There was a defect in 1.3.0, it has been fixed in the CI builds but a new build hasn't been published to the Playstore yet.

**Comment by Wilco89** [comment] 2019-12-20 13:23
When will this build be available, I do have a serious issue now, important push messages don't come to my device, and I have to rewrite a lot of lines in my automations. Ctrl+h but still a lot. 

And also reinstall html5 push notifications to get notifications on my device

**Comment by JBassett** [comment] 2019-12-20 13:39
@Wilco89 It's being promoted as we speak, might take up to an hour or so to be available from the Playstore.

**Comment by Wilco89** [comment] 2019-12-20 17:19
> @Wilco89 It's being promoted as we speak, might take up to an hour or so to be available from the Playstore.

UPDATE is there, did install, now new notify.mobile_app_inserted_name is created. But when I do a test message, it doesn't arrive.
