### ISSUE TITLE
Add support for reporting alarms

### ISSUE THREAD

**Issue by tiagofreire-pt** [home-assistant/home-assistant-android#439] opened 2020-02-17 11:21 UTC
**Home Assistant Android version:** 
Last commit available on github.

**Android version:**
9.0

**Phone model:**
Samsung Galaxy J7 2017

**Home Assistant version:**
0.105.4

**Last working Home Assistant release (if known):**
N/A

**Description of problem:**

The full integration of an android smartphone with its main status reported to Home Assistant would improve the data available for automations regarding the phone states:

The android intents for Alarms (specifically for Samsung phones using the manufaturer alarm clock app):
- com.samsung.sec.android.clockpackage.alarm_ALARM_STOPPED_IN_ALERT
- com.samsung.sec.android.clockpackage.alarm_ALARM_ALERT

Android alarm intents:
com.android.alarmclock.ALARM_ALERT
com.android.deskclock.ALARM_ALERT

Sony alarm intent:
com.sonyericsson.alarm.ALARM_ALERT

The possibility to also report to HA the alarm time and recurrence would be awesome for automations regarding timers, routines and voice assistants.

This full integration on the HA app would require less complexity, resources used by a bunch of apps and generally more efficient workflow and HA configuration.

**Comments** 

Related to https://github.com/home-assistant/home-assistant-android/issues/201#issuecomment-584741995.

**Comment by dshokouhi** [comment] 2020-02-17 18:26
Are the alarm intents really split up like that by manufacturer? That seems like a lot to account for. Shouldn't all devices have the default android one?

**Comment by paravoid** [comment] 2020-02-18 02:37
Isn't this a duplicate of #56? There is some additional context there.

**Comment by robbiet480** [comment] 2020-02-18 02:53
Yep, thanks for catching @paravoid

**Closed by robbiet480** 2020-02-18 02:53 UTC
Labels: enhancement, sensor-tracking
