### ISSUE TITLE
Allow icons in notifications

### ISSUE THREAD

**Issue by mdrichardson** [home-assistant/home-assistant-android#474] opened 2020-02-25 16:19 UTC
**Is your feature request related to a problem? Please describe.**
Images are okay, but if I just want an icon, I don't really like how images look when expanded in the notification pane. I'd rather be able to set an icon and not have it expand into an image. [I think this is supported by Android](https://firebase.google.com/docs/reference/admin/node/admin.messaging.AndroidNotification#optional-icon)

**Describe the solution you'd like**
Allow the `icon` property for notifications

**Describe alternatives you've considered, if any**
Just use `image`, instead

**Comment by dshokouhi** [comment] 2020-02-25 16:21
Duplicate of #162

**Closed by dshokouhi** 2020-02-25 16:21 UTC
Labels: enhancement
