### ISSUE TITLE
Open external URLs in default browser

### ISSUE THREAD

**Issue by Kisty** [home-assistant/home-assistant-android#75] opened 2019-11-26 11:59 UTC
Would be good to perhaps get the app to open external links in the browser. I managed to get back to log in by pressing back which logged me out of HA :(.

This can be done by using [shouldOverrideUrlLoading](https://developer.android.com/reference/android/webkit/WebViewClient.html#shouldOverrideUrlLoading(android.webkit.WebView,%20java.lang.String)).

The only issue I can see about this is that there might be instances where you want authenticate using the HA OAuth for account linking or possibly other things.

**Comment by balloob** [comment] 2019-11-26 16:37
OAuth account linking should work just fine in an external browser, as the authorize callback endpoints do not require authentication.

**Comment by fanaticDavid** [comment] 2019-12-07 03:38
I have my Home Assistant instance running behind an NGINX reverse proxy. To add an extra layer of security, I set up NGINX to use Google OAuth. When I manually enter the URL to reach my HA instance, it shows me the "Sign in with Google" button (as it should) but when I tap that, I get this error:

![Screenshot_20191207-043212_Home Assistant](https://user-images.githubusercontent.com/20402931/70368474-438cda00-18ab-11ea-9a78-98747c64292c.jpg)

Would this enhancement fix that problem?

**Comment by balloob** [comment] 2019-12-07 19:54
@fanaticDavid that is a duplicate of #45

**Comment by ve6rah** [comment] 2019-12-22 23:56
As another data point, I have a weblink set up in HA that I click on that has its own authentication. Opening it in a browser allows me to enter username/password, however if I click the link from within the HA app it skips authentication and just goes straight to the not authorized error.

I'd love to see either the option to open these links in an external browser, or for the internal browser to support authenticated websites.

**Comment by jmiedzinski** [comment] 2020-01-06 17:26
> When I manually enter the external URL to reach my HA instance, it shows me the "Sign in with Google" button (as it should) but when I tap that, I get a 403 error: `disallowed_useragent`
> 

This is because of:
_As of April 20, 2017, Google has blocked OAuth authorization requests via web views. Unfortunately, a lot of developers have not migrated their current apps away from using embedded browsers to make such requests. Therefore, users trying to use their Google accounts to sign in to third party apps that still make use of web views for OAuth logins constantly get the dreaded 403 disallowed_useragent error._

More info here:
https://auth0.com/blog/google-blocks-oauth-requests-from-embedded-browsers/

I also stuck on this, so +1 for handling authentication in external browser

**Comment by gadgetchnnel** [comment] 2020-01-07 18:50
Another reason for this is links which can be opened in a native Android app, for example links to Reddit posts (I have a feed of these in HA). In the old PWA these will open in the Reddit app. In the new app they will open the Reddit site in the webview, and clicking the option to open in the app fails with net::ERR_UNKNOWN_URL_SCHEME

**Closed** 2020-01-08 22:55 UTC
Labels: enhancement
