### ISSUE TITLE
device_tracker and geocoded location information are out of sync

### ISSUE THREAD

**Issue by fineemb** [home-assistant/home-assistant-android#508] opened 2020-03-08 11:48 UTC
**Home Assistant Android version:**
1.8.0-153
**Android version:**
android 10
**Phone model:**
xiaomi mix2s
**Home Assistant version:**
0.106.2
**Last working Home Assistant release (if known):**
0.106.2
**Description of problem:**
device_tracker and geocoded location, gps information is out of sync. It appears that geocoded location has been updated, but device_tracker has not been updated for a long time
**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by andriej** [comment] 2020-03-08 12:50
On latest play beta version I have quite different situation - geocode is out of sync for few hours while other geolocation is updated properly. Only for one out of two phones (android 10, oneplus 6)

**Comment by dshokouhi** [comment] 2020-03-08 16:42
Duplicate of #497 see the issue for why these 2 are not in sync

**Closed by dshokouhi** 2020-03-08 16:42 UTC
Labels: bug
