### ISSUE TITLE
Feature request: notification tag

### ISSUE THREAD

**Issue by bieniu** [home-assistant/home-assistant-android#354] opened 2020-02-09 20:30 UTC
**Home Assistant Android version:** 1.6.0

**Android version:** 10

**Phone model:** OnePlus 6

**Home Assistant version:** 0.105.2

**Last working Home Assistant release (if known):** None

**Description of problem:**
Tag is the unique identifier of the notification. Can be overridden when sending a notification to allow for replacing existing notifications. Now I add `tag` like this:
```
title: 'Title'
message: 'Body'
data:
  android:
    notification:
      title: 'Title'
      body: 'Body'
      tag: 'unique-string'
```
But this way will soon be [disabled](https://github.com/home-assistant/mobile-apps-fcm-push/pull/5).
Any chance to add this feature?

**Comment by hmmbob** [comment] 2020-02-09 20:31
Duplicate of #353

**Comment by andriej** [comment] 2020-02-09 20:32
@hmmbob not really duplicate, as #353 is about dismissing of notification, while tag is quite different functionality

+1 for the tags

**Comment by hmmbob** [comment] 2020-02-09 20:50
The update functionality asked there is based on tag. It is a duplicate.

**Comment by bieniu** [comment] 2020-02-09 21:05
@hmmbob Tag is more general feature. Notification update is based on tag. The tag itself gives more possibilities. For example, sending to HA information about notification dismiss by the user.

**Closed** 2020-02-11 03:14 UTC
