### ISSUE TITLE
Implement full screen of app

### ISSUE THREAD

**Issue by barrymossel** [home-assistant/home-assistant-android#134] opened 2019-12-11 14:57 UTC
Please implement fullscreen through: https://developer.android.com/training/system-ui/navigation
Should be possible as its also possible for the frontend through Chrome...

**Comment by dshokouhi** [comment] 2019-12-11 16:30
Duplicate of #59

**Comment by robbiet480** [comment] 2019-12-11 18:51
Closing in favor of #59

**Closed by robbiet480** 2019-12-11 18:51 UTC

**Comment by barrymossel** [comment] 2019-12-13 16:29
> Closing in favor of #59

But that one is closed, right. Thought no-one would look there anyway. And I believe the question is mis-understood there. Not the UI should be fullscreen, but rather the app (so the shell). The UI will adapt to the shell anyway I reckon, just like on a monitor...
