### ISSUE TITLE
Certificate Authentication

### ISSUE THREAD

**Issue by hulbs9nw** [home-assistant/home-assistant-android#496] opened 2020-03-04 10:17 UTC
**Home Assistant Android version:**
1.8.0-144
**Android version:**
9
**Phone model:**
Moto G6 Plus
**Home Assistant version:**
0.1604.4
**Last working Home Assistant release (if known):**
N/A
**Description of problem:**
I use nginx in front of my HA installation with certificate based authentication.  When I connect using a browser I'm prompted for which certificate I want to use to authenticate via nginx.  Unfortunately the Home assistant app doesn't prompt me for the certificate and I get a 403 Forbidden as I cannot successfully authenticate.
**Traceback (if applicable):**
N/A
```

```

**Screenshot of problem:**
![Screenshot_20200304-101140](https://user-images.githubusercontent.com/8561002/75869395-67f04800-5e01-11ea-9b3f-34abba6ba783.png)

**Additional information:**

**Comment by neopilou** [comment] 2020-03-04 12:53
I presume it's not a bug but an enhancement. Actually, it's just not yet managed by the app.

**Comment by dshokouhi** [comment] 2020-03-04 15:40
Duplicate of #27 #214 #442 

Please refer to those bugs for the reason why.

**Closed by dshokouhi** 2020-03-04 15:40 UTC
Labels: bug

**Comment by hulbs9nw** [comment] 2020-03-04 15:47
Apologies I did search but missed those somehow.  I get the reasoning, thanks for responding.
