### ISSUE TITLE
Unable to register application

### ISSUE THREAD

**Issue by mathieu-mp** [home-assistant/home-assistant-android#378] opened 2020-02-11 20:19 UTC
**Home Assistant Android version: 1.6.0**

**Android version: 9**

**Phone model: OnePlus A5000**

**Home Assistant version: 0.105.3**

**Last working Home Assistant release (if known): none**

**Description of problem:**
After login to Home Assistant instance, fullscreen "Unable to register application" and no device_tracker is created under Home Assistant instance. If I kill the mobile app, the error won't display any more, and I can display home assistant dashboard but the device_tracker still isn't created.

**Additional information:**

I tried to reinstall the app, to clear the cache and the app data. Not successful.
This is the only phone that won't login. Other phone logins and appears as device_tracker.

I noticed in the app settings that the device name is empty by default.

**Comment by dshokouhi** [comment] 2020-02-11 21:48
Seems to be a duplicate of #132

**Closed** 2020-02-11 22:52 UTC
Labels: onboarding
