### ISSUE TITLE
New functionnalities

### ISSUE THREAD

**Issue by k2v1n58** [home-assistant/home-assistant-android#329] opened 2020-02-01 09:48 UTC
Is it possible to have 2 new functionalities:

- Switch screen off (similar to Fully kiosk) that can be used with browser_mod (browser_mod.blackout)
- Keep screen ON to prevent the screen to switch off automatically

**Comment by balloob** [comment] 2020-02-02 05:27
Duplicate of #325

**Closed by balloob** 2020-02-02 05:27 UTC
