### ISSUE TITLE
Long SSID with spaces break app?

### ISSUE THREAD

**Issue by andriej** [home-assistant/home-assistant-android#240] opened 2020-01-08 23:10 UTC
**Home Assistant Android version:** 71 latest firebase

**Android version:** 10

**Phone model:** OnePlus 6

**Home Assistant version:** 0.103.x latest

**Last working Home Assistant release (if known):** n/a

**Description of problem:**
After installing latest firebase version configuration worked, but putting SSID of my network make it crash, loose all config and never work again.
My SSID is
"Xxxxx Yyyyyy, zzzzzz"
(include spaces and coma and is quite long)

Also I don't put internal URL as it's the same as remote.

**Traceback (if applicable):**

```
not available

```

**Additional information:**

**Comment by schildgenb** [comment] 2020-01-09 04:26
I have the same issue once I put the SSID in the app has an issue and either takes me back to the settings or crashes. I also have spaces in my SSID. The app also pops up a message to stating to check your internet settings.

**Comment by JBassett** [comment] 2020-01-10 02:10
The issue isn't with the SSID, it's with the fact that the local url is missing.  Making a PR to correct.

**Comment by schildgenb** [comment] 2020-01-10 02:34
I have entered a local url and it will show the web view but it still has the pop up to check my settings. If I do not remove the SSID it then crashes.

**Comment by JBassett** [comment] 2020-01-10 02:36
@schildgenb that will be fixed by https://github.com/home-assistant/home-assistant-android/pull/245

**Closed** 2020-01-10 18:51 UTC
Labels: bug
