### ISSUE TITLE
Feature request: add URL option for push notification

### ISSUE THREAD

**Issue by funkbuddha** [home-assistant/home-assistant-android#335] opened 2020-02-02 20:38 UTC
I need to send a URL from my NVR to my phone via a push notification so that when I tap the notification, it takes me to the NVR’s recording that generated the alert. 

Something like this

message: 'test message'
data:
  android:
    notification:
      url: https://www.google.com
      

Thanks!

**Comment by allanpersson** [comment] 2020-02-02 21:12
Duplicate of https://github.com/home-assistant/home-assistant-android/issues/162 🙏

**Closed** 2020-02-11 03:14 UTC
