### ISSUE TITLE
Feature request: Support for Client Certificate Authentication

### ISSUE THREAD

**Issue by m11tch** [home-assistant/home-assistant-android#442] opened 2020-02-17 20:28 UTC
**Home Assistant Android version:**
1.7.2-128
**Android version:**
9
**Phone model:**
Huawei P20 Lite (ANE-LX1)
**Home Assistant version:**
0.105.4
**Last working Home Assistant release (if known):**
N/A
**Description of problem:**
I use nginx to expose home-assistant to the outside world, to keep bad guys away I set up SSL client certificate authentication. While this works fine for 'chrome pinned websites' it does not work for the home-assistant app. (there is no way of selecting the certificate to be used for authentication.) 

It would be great if support for SSL Client Certificate Authentication could somehow be added. 

**Traceback (if applicable):**

```

```

**Screenshot of problem:**
![photo5934035921664061771](https://user-images.githubusercontent.com/5503199/74684359-f93da880-51cb-11ea-9cdf-38cd37b06eca.jpg)

**Additional information:**
Example for setting up Client Certificate Authentication in nginx: https://gist.github.com/mtigas/952344

**Comment by robbiet480** [comment] 2020-02-17 21:34
Duplicate of #27 and #214. Please search before opening new issues.

**Closed by robbiet480** 2020-02-17 21:34 UTC

**Comment by dmpolukhin** [comment] 2020-02-21 09:19
@robbiet480 could you please explain current status of client certificate support in Android app. As far as I can see all issues that you mentioned are closed but in current app version 1.7.2-128 problem still exists. In my setup client certificate works perfectly in Chrome browser but HA app cannot connect and doesn't even show prompt for certificate selection. Basic authorization on reverse proxy also doesn't work because HA overwrite auth header https://github.com/home-assistant/home-assistant.io/issues/6350 and resolution is "won't fix". iOS story for client certificate https://github.com/home-assistant/home-assistant-iOS/issues/27.

Does it mean that the resolution of the client certificate support issue is also "won't fix" for Android?

**Comment by robbiet480** [comment] 2020-02-21 19:01
Client certificates are currently not supported and we have no plans to implement such a feature as it has been deemed too complex and we are too early in the apps life to get there. Would rather be spending time on implementing features that provide value to all users, like better notifications and more sensors.

**Comment by bryanyork** [comment] 2020-02-24 07:50
That's a shame. BTW it seems like OpenHab supports this on their app. Will try and see if I can port over their implementation. Would be great to avoid forks.

https://github.com/openhab/openhab-android/blob/72389b8837ab1aec3aa2c7f1d277d4959f4579e4/mobile/src/main/java/org/openhab/habdroid/ui/ConnectionWebViewClient.kt#L74

**Comment by ohmer1** [comment] 2020-02-29 01:50
I'm using an nginx reverse proxy with client certificate too. Unfortunately, I can't use the app because it doesn't support client certificate.

**Comment by Hubro** [comment] 2020-11-10 10:15
I am extremely nervous about opening up my HA install to the internet without support for client certificates :/

**Comment by fjh40** [comment] 2021-08-15 22:32
Just to add to this, I would love to be able to use client certificates as well. Doesn't makes sense considering all the devices connected to the internet in 2021 to not use every bit of security you have. For location tracking for example / convenience in general being able to access home assistant without turning on Wireguard is a huge must.

**Comment by jnxxx** [comment] 2021-09-05 19:59
+1

**Comment by HeyVern** [comment] 2021-10-13 20:15
+1

**Comment by bazuchan** [comment] 2022-04-16 12:02
+1

**Comment by HeyVern** [comment] 2022-04-16 12:06
+1

**Comment by GrzegorzDrozd** [comment] 2023-03-13 14:27
> Client certificates are currently not supported and we have no plans to implement such a feature as it has been deemed too complex and we are too early in the apps life to get there.

@robbiet480 @balloob It has been 3 years. Are we there yet?
