### ISSUE TITLE
hyperlinks in markdown card not clickable

### ISSUE THREAD

**Issue by SamJongenelen** [home-assistant/home-assistant-android#136] opened 2019-12-11 16:48 UTC
I have some handy hyperlinks in a panel in my lovelace. (For init backup of hassio)
However, the links are not opening on click.
Could not find a related issue in the repo. I hope my short report is clear enough.

Android, android10

**Comment by balloob** [comment] 2019-12-12 05:39
Are the links relative, point at other domains?

**Comment by SamJongenelen** [comment] 2019-12-12 20:16
Both http and https links to absolute URLs are used; local DNS name, IP and FQDN all do not work

**Comment by quthla** [comment] 2019-12-12 20:19
Are these supposed to open in another window / tab?

**Comment by SamJongenelen** [comment] 2019-12-12 20:35
Ah no, they are declared as _plain_ http strings in an MD file. (without actual markdown used). 

If i use an inline style link in the MD, it works like expected.  

I expected the _plain_ link to work, because the links actually do have the hyperlink color

**Comment by quthla** [comment] 2019-12-12 21:02
It is what I expected. The markdown card automatically converts urls to an anchor with target _blank but the app does currently not support opening external windows.

**Comment by SamJongenelen** [comment] 2019-12-12 21:24
Ah yes thank you. Is there any issue i can track regarding the this?

**Comment by balloob** [comment] 2019-12-13 08:45
Duplicate of #75

**Closed by balloob** 2019-12-13 08:45 UTC
Labels: bug
